### ISSUE TITLE
Add https support

### ISSUE THREAD

**Issue by bryanbraun** [jacopocolo/Hex-clock#3]
If you Google "Hex Clock" the top result returns an `https` address.

![image](https://user-images.githubusercontent.com/1256329/56228752-692c5100-6046-11e9-8f8c-06d2af527522.png)

Browsing with an https results in a blank white screen and several console errors.

![image](https://user-images.githubusercontent.com/1256329/56228873-ae508300-6046-11e9-8e19-aed25fedbf80.png)

**Comment by jacopocolo** [comment]
Hey @bryanbraun, thanks for reporting this! Fixed it! :)
